### ISSUE TITLE
'package:flutter/src/widgets/overlay.dart': Failed assertion: line 207 pos 12: '_overlay != null': is not true.

### ISSUE THREAD

**Issue by shahmirzali49** [maheshj01/searchfield#43]
**Describe the bug**

Unhandled Exception: Bad state: Cannot add new events after calling close 

When I used second-time SearchField, I didn't know why it gave me this error.

sorry I don't have wide info about error.

edited:
Issue reproduces with latest v0.9.9
<details>
<summary>minimal code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:searchfield/searchfield.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Material App',
      home: BottomNavBarHome(),
    );
  }
}

class BottomNavBarHome extends StatefulWidget {
  const BottomNavBarHome({Key? key}) : super(key: key);

  @override
  State<BottomNavBarHome> createState() => _BottomNavBarHomeState();
}

class _BottomNavBarHomeState extends State<BottomNavBarHome> {
  late PageController _pageController;
  late final GlobalKey<State<BottomNavigationBar>> _bottomNavBarKey;
  DateTime? currentBackPressTime;
  @override
  void initState() {
    _pageController = PageController();
    _bottomNavBarKey = GlobalKey<State<BottomNavigationBar>>();
    super.initState();
  }

  int selectindex = 0;
  void _onItemTapped(int selectedIndex) {
    setState(() {
      selectindex = selectedIndex;
      _pageController.jumpToPage(selectindex);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Scaffold(
        extendBody: true,
        body: PageView(
          controller: _pageController,
          children: [
            PageOne(
              bottomNavBarKey: _bottomNavBarKey,
            ),
            PageSecond(),
            PageThird(),
          ],
          // onPageChanged: _onPageChanged,
        ),
        bottomNavigationBar: BottomNavigationBar(
          currentIndex: selectindex,
          type: BottomNavigationBarType.fixed,
          key: _bottomNavBarKey,
          onTap: _onItemTapped,
          items: const [
            BottomNavigationBarItem(
              icon: Icon(Icons.home),
              label: 'Page 1',
              backgroundColor: Colors.blue,
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.person),
              label: 'Page 2',
              backgroundColor: Colors.blue,
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.book),
              label: 'Page 3',
              backgroundColor: Colors.blue,
            ),
          ],
        ),
      ),
    );
  }
}

class PageOne extends StatefulWidget {
  const PageOne({Key? key, required this.bottomNavBarKey}) : super(key: key);

  final GlobalKey<State<BottomNavigationBar>> bottomNavBarKey;

  @override
  State<PageOne> createState() => _PageOneState();
}

class _PageOneState extends State<PageOne> {
  final List<String> _suggestions = [
    'United States',
    'Germany',
    'Washington',
    'Paris',
    'Jakarta',
    'Australia',
    'India',
    'Czech Republic',
    'Lorem Ipsum',
  ];

  BottomNavigationBar? bottomNavKey;

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(8.0),
        child: SearchField(
          suggestionState: Suggestion.expand,
          suggestionAction: SuggestionAction.unfocus,
          suggestions: _suggestions.map((e) => SearchFieldListItem(e)).toList(),
          textInputAction: TextInputAction.done,
          hint: 'SearchField Example 1',
          autoCorrect: false,
          maxSuggestionsInViewPort: 3,
          itemHeight: 45,
          onSuggestionTap: (x) async {
            if (widget.bottomNavBarKey.currentWidget != null) {
              bottomNavKey =
                  widget.bottomNavBarKey.currentWidget as BottomNavigationBar;
            }
            bottomNavKey?.onTap!(1);
          },
        ),
      ),
    );
  }
}

class PageSecond extends StatelessWidget {
  const PageSecond({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(child: Text('Page Second')),
    );
  }
}

class PageThird extends StatelessWidget {
  const PageThird({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
          child: Text(
        'Page Third',
      )),
    );
  }
}

```
</details> 

<details>
<summary>logs</summary>

```
Restarted application in 1,876ms.
D/EGL_emulation( 6657): app_time_stats: avg=4548.26ms min=4548.26ms max=4548.26ms count=1
D/InputMethodManager( 6657): showSoftInput() view=io.flutter.embedding.android.FlutterView{6bfaeb4 VFE...... .F...... 0,0-1440,3064 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController( 6657): show(ime(), fromIme=true)
D/EGL_emulation( 6657): app_time_stats: avg=11220.27ms min=5.66ms max=168162.59ms count=15
D/EGL_emulation( 6657): app_time_stats: avg=5991.23ms min=5991.23ms max=5991.23ms count=1
D/EGL_emulation( 6657): app_time_stats: avg=46.64ms min=5.86ms max=502.45ms count=22
D/EGL_emulation( 6657): app_time_stats: avg=314.47ms min=3.32ms max=6142.25ms count=20
D/EGL_emulation( 6657): app_time_stats: avg=5358.02ms min=5358.02ms max=5358.02ms count=1
D/InputMethodManager( 6657): showSoftInput() view=io.flutter.embedding.android.FlutterView{6bfaeb4 VFE...... .F...... 0,0-1440,3064 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/EGL_emulation( 6657): app_time_stats: avg=1785.92ms min=16.31ms max=8787.12ms count=5
D/InsetsController( 6657): show(ime(), fromIme=true)
D/EGL_emulation( 6657): app_time_stats: avg=613.65ms min=4.96ms max=9016.41ms count=15
D/EGL_emulation( 6657): app_time_stats: avg=66.43ms min=5.82ms max=505.28ms count=21
D/EGL_emulation( 6657): app_time_stats: avg=377.43ms min=140.98ms max=496.75ms count=3
D/EGL_emulation( 6657): app_time_stats: avg=715.01ms min=4.28ms max=13469.75ms count=19
D/EGL_emulation( 6657): app_time_stats: avg=1663.22ms min=11.73ms max=11548.72ms count=7

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
'package:flutter/src/widgets/overlay.dart': Failed assertion: line 207 pos 12: '_overlay != null': is not true.

When the exception was thrown, this was the stack:
#2      OverlayEntry.remove (package:flutter/src/widgets/overlay.dart:207:12)
#3      _SearchFieldState.dispose (package:searchfield/src/searchfield.dart:374:22)
#4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5867:11)
#5      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2097:13)
#6      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2095:7)
#7      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6940:14)
#8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2093:13)
#9      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2095:7)
#10     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6940:14)
#11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2093:13)
#12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2095:7)
#13     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5704:14)
#14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2093:13)
#15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2095:7)
#16     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6940:14)
#17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2093:13)
#18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2095:7)
#19     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6940:14)
#20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2093:13)
#21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2095:7)
#22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5704:14)
#23     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2093:13)
#24     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2095:7)
#25     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5704:14)
#26     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2093:13)
#27     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2095:7)
#28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5704:14)
#29     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2093:13)
#30     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2095:7)
#31     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5704:14)
#32     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2093:13)
#33     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2095:7)
#34     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5704:14)
#35     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2093:13)
#36     ListIterable.forEach (dart:_internal/iterable.dart:49:13)
#37     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:2106:25)
#38     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2799:15)
#39     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3234:7)
#40     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:992:19)
#41     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#42     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#43     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#44     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#45     _invoke (dart:ui/hooks.dart:312:13)
#46     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
#47     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════
D/EGL_emulation( 6657): app_time_stats: avg=31784.69ms min=31784.69ms max=31784.69ms count=1

```
</details>

**Comment by Shahmirzali-Huseynov** [comment]
when I click the error line in debug console.

<img width="1046" alt="Screen Shot 2022-08-08 at 01 32 06" src="https://user-images.githubusercontent.com/49102327/183311707-f32893dd-620e-4a0a-89c6-5c541165b119.png">

**Comment by Shahmirzali-Huseynov** [comment]
my code

```
Form(
                              key: _soldierFormKey,
                              child: SearchField<FilterModel>(
                                suggestions: birthPlaceList
                                    .map(
                                      (e) => SearchFieldListItem<FilterModel>(e.title,
                                          item: e,
                                          child: Text(
                                            e.title,
                                            style: CustomTextStyles(context).headline5(
                                              fontWeight: FontWeight.normal,
                                              darkThemeColor: Colors.black,
                                              lightThemeColor: Colors.black,
                                            ),
                                          )),
                                    )
                                    .toList(),
                                suggestionState: Suggestion.expand,
                                textInputAction: TextInputAction.done,
                                hint: langTranslation!.search,
                                hasOverlay: false,
                                autoCorrect: false,
                                suggestionAction: SuggestionAction.unfocus,
                                searchStyle: CustomTextStyles(context).headline5(
                                  fontWeight: FontWeight.w500,
                                  darkThemeColor: Colors.black,
                                  lightThemeColor: Colors.black,
                                ),
                                validator: (validatorText) {
                                  if (validatorText != null && validatorText.isEmpty) {
                                    return null;
                                  } else if (validatorText != null &&
                                      !ref.read(containBirthPlaceProvider(validatorText))) {
                                    return "";
                                  } else if (validatorText != null &&
                                      ref.read(containBirthPlaceProvider(validatorText))) {
                                    int id = ref.read(getIdFromBirthPlaceListProvider(validatorText));
                                    placeId = id;
                                    print(" placeId $placeId ");
                                    ref.refresh(searchProvider).getSearchViewModel(
                                          soldierId: ref.refresh(soldierIdProvider.notifier).update((state) => 0),
                                          birthPlaceId: placeId,
                                        );
                                    ref.refresh(statusControlProvider.notifier).update((state) => null);

                                    bottomNavKey?.onTap!(1);
                                    return null;
                                  } else {
                                    return null;
                                  }
                                },
                                controller: _textEditingController,
                                searchInputDecoration: filterFormFieldDecoration(
                                  contentPaddingHorizontal: 20.w,
                                  contentPaddingVertical: 1.sm,
                                  context: context,
                                  errorBorderWidth: 2,
                                  suffixIcon: Row(
                                    mainAxisAlignment: MainAxisAlignment.end,
                                    mainAxisSize: MainAxisSize.min,
                                    children: [
                                      IconButton(
                                        splashColor: Colors.transparent,
                                        highlightColor: Colors.transparent,
                                        padding: EdgeInsets.zero,
                                        constraints: const BoxConstraints(minWidth: 1, minHeight: 1),
                                        splashRadius: 0.1,
                                        onPressed: () {
                                          
                                        },
                                        icon: const Icon(
                                          Icons.search,
                                          color: Colors.blue,
                                        ),
                                      ),
                                      IconButton(
                                        splashColor: Colors.transparent,
                                        highlightColor: Colors.transparent,
                                        splashRadius: 0.1,
                                        onPressed: () {
                                         
                                        },
                                        icon: const Icon(
                                          Icons.place_outlined,
                                          color: Colors.blue,
                                        ),
                                      ),
                                    ],
                                  ),
                                  errorStyle: const TextStyle(height: 0, color: Colors.transparent),
                                ),
                                onSubmit: (textValue) => _soldierFormKey.currentState?.validate(),
                                maxSuggestionsInViewPort: 3,
                                emptyWidget: Container(
                                  // height: 50,
                                  width: double.infinity,
                                  padding: EdgeInsets.only(
                                    top: 15.h,
                                    bottom: 15.h,
                                    left: 10.w,
                                  ),
                                  color: whiteColor,
                                  child: Text(
                                    langTranslation.noresult,
                                    style: CustomTextStyles(context).headline5(
                                      fontWeight: FontWeight.normal,
                                      darkThemeColor: Colors.black,
                                      lightThemeColor: Colors.black,
                                    ),
                                    // textAlign: TextAlign.center,
                                  ),
                                ),
                                itemHeight: 45.h,
                                onSuggestionTap: (SearchFieldListItem<FilterModel> value) {
                                  placeId = value.item?.id;
                                  _soldierFormKey.currentState?.validate();
                                },
                              ),
                            ),
```

**Comment by maheshmnj** [comment]
HI @Shahmirzali-Huseynov, Thanks for filing the issue. Can you please try using fix-17 branch as mentioned here https://github.com/maheshmnj/searchfield/issues/17#issuecomment-1200108227 , I believe that issue is fixed.

**Comment by maheshmnj** [comment]
Also see https://github.com/maheshmnj/searchfield/issues/17#issuecomment-1207684032

**Comment by Shahmirzali-Huseynov** [comment]
@maheshmnj  thanks for replying, but I used 0.6.8 version of the package, but isn't fixed. the same error.

**Comment by Shahmirzali-Huseynov** [comment]
@maheshmnj Actually I noticed this error happen when I use GlobalKey for changing bottom nav. 

`bottomNavKey?.onTap!(1);`

**Comment by maheshmnj** [comment]
Thanks for the update @Shahmirzali-Huseynov, Can you please share a minimal and complete sample code? which I can directly run with minimal or no code changes. You may use the [example app](https://github.com/maheshmnj/searchfield/blob/master/example/lib/example1.dart) to share the reproducible code

**Comment by Shahmirzali-Huseynov** [comment]
I will, but unfortunately, I don't have time now, but I will try this week, and also I don't understand how the error is gone. but whatever I will do the minimal and complete sample code.

**Comment by maheshmnj** [comment]
sure no worries take your time. And thank you so much for helping out to improve this package.

**Comment by Shahmirzali-Huseynov** [comment]
@maheshmnj  sorry for the delay. this is the minimal and complete sample code. 

[flutter_searchfield_issue.zip](https://github.com/maheshmnj/searchfield/files/9444745/flutter_searchfield_issue.zip)

**Comment by maheshmnj** [comment]
Thanks will take a look at it

**Comment by maheshmnj** [comment]
@Shahmirzali-Huseynov Can you please explain what are the steps to reproduce the issue? I am unable to reproduce the error with your code sample. (I verified on macOS desktop app)

**Comment by maheshmnj** [comment]
Can you also test with new release v0.7.0?

**Comment by Shahmirzali-Huseynov** [comment]
I tested but the problem is continuing. I share with you the screen record. 
[Screen Recording 2022-08-30 at 17.02.36.zip](https://github.com/maheshmnj/searchfield/files/9453018/Screen.Recording.2022-08-30.at.17.02.36.zip)

**Comment by maheshmnj** [comment]
@Shahmirzali-Huseynov  sorry for the delay please try version 0.7.1.

**Comment by Shahmirzali-Huseynov** [comment]
I tried but was not solved, again -> 
<img width="990" alt="Screen Shot 2022-10-09 at 19 17 49" src="https://user-images.githubusercontent.com/49102327/194767813-6896c9ad-dd94-4c8d-941a-4e9d6991f735.png">

**Comment by maheshmnj** [comment]
Thanks for the update @Shahmirzali-Huseynov Looks like the widget is getting disposed of because of the Global key, removing the code in `didChangeDependencies` doesn't reproduce the issue, Theres definetly something wrong, I 'll need to figure that out.

```dart
final GlobalKey<State<BottomNavigationBar>> bottomNavBarKey;

  @override
  void didChangeDependencies() {
    if (widget.bottomNavBarKey.currentWidget != null) {
      bottomNavKey =
          widget.bottomNavBarKey.currentWidget as BottomNavigationBar;
    }
    super.didChangeDependencies();
  }
``` 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:searchfield/searchfield.dart';

class PageOne extends StatefulWidget {
  const PageOne({Key? key, required this.bottomNavBarKey}) : super(key: key);

  final GlobalKey<State<BottomNavigationBar>> bottomNavBarKey;

  @override
  State<PageOne> createState() => _PageOneState();
}

class _PageOneState extends State<PageOne> {
  final List<String> _suggestions = [
    'United States',
    'Germany',
    'Washington',
    'Paris',
    'Jakarta',
    'Australia',
    'India',
    'Czech Republic',
    'Lorem Ipsum',
  ];

  BottomNavigationBar? bottomNavKey;

  @override
  void didChangeDependencies() {
    if (widget.bottomNavBarKey.currentWidget != null) {
      bottomNavKey =
          widget.bottomNavBarKey.currentWidget as BottomNavigationBar;
    }
    super.didChangeDependencies();
  }

  final _searchController = TextEditingController();
  final _formKey = GlobalKey<FormState>();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: ListView(
        children: <Widget>[
          const SizedBox(
            height: 100,
          ),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: SearchField(
              suggestionState: Suggestion.expand,
              suggestionAction: SuggestionAction.unfocus,
              suggestions:
                  _suggestions.map((e) => SearchFieldListItem(e)).toList(),
              textInputAction: TextInputAction.done,
              controller: _searchController,
              hint: 'SearchField Example 1',
              hasOverlay: false,
              autoCorrect: false,
              maxSuggestionsInViewPort: 3,
              itemHeight: 45,
              onSuggestionTap: (x) async {
                bottomNavKey?.onTap!(1);
              },
            ),
          ),
        ],
      ),
    );
  }
}

```
</details>

**Comment by Shahmirzali-Huseynov** [comment]
maybe the problem is in the function that runs or responds after the widget dispose.

**Comment by maheshmnj** [comment]
@shahmirzali49 Could you please try the latest version of the plugin?

Thanks

**Comment by shahmirzali49** [comment]
Unfortunately, my project got old and I tried to run but there was an error I couldn't fix.

**Comment by maheshmnj** [comment]
No worries, I am going to close this issue for now. In case you still encounter the issue please free to file a new issue and I would be happy to review

**Comment by shahmirzali49** [comment]
> @maheshmnj sorry for the delay. this is the minimal and complete sample code.
> 
> [flutter_searchfield_issue.zip](https://github.com/maheshmnj/searchfield/files/9444745/flutter_searchfield_issue.zip)

actually you can test the issue

**Comment by maheshmnj** [comment]
> > @maheshmnj sorry for the delay. this is the minimal and complete sample code.
> > 
> > [flutter_searchfield_issue.zip](https://github.com/maheshmnj/searchfield/files/9444745/flutter_searchfield_issue.zip)
> 
> actually, if you want, you can test the issue

@shahmirzali49 is the bug still reproducible on the latest version of the package 0.9.7?

**Comment by maheshmnj** [comment]
No worries, thanks for the sample code I will take a look.

**Comment by maheshmnj** [comment]
@shahmirzali49 The code is not downloadable can you please reupload?

**Comment by shahmirzali49** [comment]
sorry for the delay

[flutter_searchfield_issue.zip](https://github.com/maheshmnj/searchfield/files/14654264/flutter_searchfield_issue.zip)

**Comment by maheshmnj** [comment]
minimal reproducible code

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:searchfield/searchfield.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Material App',
      home: BottomNavBarHome(),
    );
  }
}

class BottomNavBarHome extends StatefulWidget {
  const BottomNavBarHome({Key? key}) : super(key: key);

  @override
  State<BottomNavBarHome> createState() => _BottomNavBarHomeState();
}

class _BottomNavBarHomeState extends State<BottomNavBarHome> {
  late PageController _pageController;
  late final GlobalKey<State<BottomNavigationBar>> _bottomNavBarKey;
  DateTime? currentBackPressTime;
  @override
  void initState() {
    _pageController = PageController();
    _bottomNavBarKey = GlobalKey<State<BottomNavigationBar>>();
    super.initState();
  }

  int selectindex = 0;
  void _onItemTapped(int selectedIndex) {
    setState(() {
      selectindex = selectedIndex;
      _pageController.jumpToPage(selectindex);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Scaffold(
        extendBody: true,
        body: PageView(
          controller: _pageController,
          children: [
            PageOne(
              bottomNavBarKey: _bottomNavBarKey,
            ),
            PageSecond(),
            PageThird(),
          ],
          // onPageChanged: _onPageChanged,
        ),
        bottomNavigationBar: BottomNavigationBar(
          currentIndex: selectindex,
          type: BottomNavigationBarType.fixed,
          key: _bottomNavBarKey,
          onTap: _onItemTapped,
          items: const [
            BottomNavigationBarItem(
              icon: Icon(Icons.home),
              label: 'Page 1',
              backgroundColor: Colors.blue,
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.person),
              label: 'Page 2',
              backgroundColor: Colors.blue,
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.book),
              label: 'Page 3',
              backgroundColor: Colors.blue,
            ),
          ],
        ),
      ),
    );
  }
}

class PageOne extends StatefulWidget {
  const PageOne({Key? key, required this.bottomNavBarKey}) : super(key: key);

  final GlobalKey<State<BottomNavigationBar>> bottomNavBarKey;

  @override
  State<PageOne> createState() => _PageOneState();
}

class _PageOneState extends State<PageOne> {
  final List<String> _suggestions = [
    'United States',
    'Germany',
    'Washington',
    'Paris',
    'Jakarta',
    'Australia',
    'India',
    'Czech Republic',
    'Lorem Ipsum',
  ];

  BottomNavigationBar? bottomNavKey;

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(8.0),
        child: SearchField(
          suggestionState: Suggestion.expand,
          suggestionAction: SuggestionAction.unfocus,
          suggestions: _suggestions.map((e) => SearchFieldListItem(e)).toList(),
          textInputAction: TextInputAction.done,
          hint: 'SearchField Example 1',
          autoCorrect: false,
          maxSuggestionsInViewPort: 3,
          itemHeight: 45,
          onSuggestionTap: (x) async {
            if (widget.bottomNavBarKey.currentWidget != null) {
              bottomNavKey =
                  widget.bottomNavBarKey.currentWidget as BottomNavigationBar;
            }
            bottomNavKey?.onTap!(1);
          },
        ),
      ),
    );
  }
}

class PageSecond extends StatelessWidget {
  const PageSecond({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(child: Text('Page Second')),
    );
  }
}

class PageThird extends StatelessWidget {
  const PageThird({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
          child: Text(
        'Page Third',
      )),
    );
  }
}

```
</details>

**Comment by maheshmnj** [comment]
@shahmirzali49 I have filed the issue in flutter/flutter lets wait until it's triaged.

**Comment by maheshmnj** [comment]
Bumping down the priority unless there is anything actionable on our side.

**Comment by shahmirzali49** [comment]
sorry I didn't understand).   Do I need to do something and how can I ?

**Comment by maheshmnj** [comment]
@shahmirzali49 No you are fine.
> Bumping down the priority unless there is anything actionable on our side.

This issue cannot progress unless, theres is an update on the issue that we have filed in flutter/flutter

**Comment by murvkins** [comment]
Thank you for filing this issue with the Flutter team.  I know I said I had this issue resolved and I thought it was, but it returned and I can't replicate it in sample code.  Glad you are on it and aware.

**Comment by bgsulz** [comment]
Apologies in advance if my comment is redundant. Based on [this StackOverflow answer,](https://stackoverflow.com/questions/51443904/packageflutter-src-widgets-overlay-dart-failed-assertion-line-133-pos-12), I found the following modification to eliminate the error:

```dart
// searchfield.dart, lines 415-423
void removeOverlay() {
  if (_overlayEntry != null && _overlayEntry!.mounted) {
    isSuggestionsShown = false;
    if (_overlayEntry != null) {
      _overlayEntry?.remove();
    }
  }
  _overlayEntry = null; // <- Added line
}
```

I wish I knew why this worked. I'm very new to Flutter and I don't know what on earth I'm doing.

**Comment by klausgreiner** [comment]
Flutter 3.24.3 • channel [user-branch] • unknown source
Framework • revision 2663184aa7 (2 months ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3

**Comment by maheshj01** [comment]
Released [v1.2.5](https://pub.dev/packages/searchfield)
If anyone still encounter this error please file a new issue with more details
